import React, { useState, useEffect } from 'react';
import { api } from '../../services/api';
import { useToast } from '../../context/ToastContext';
import { UNIT_NAME, DUTY_TYPES, LEAVE_TYPES, TRADES, RANKS } from '../../utils/constants';
import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  FileText,
  Printer,
  Download,
  Calendar,
  RefreshCw,
  Eye,
  Filter,
  Users,
  Shield,
  AlertTriangle,
} from 'lucide-react';
import { format } from 'date-fns';

const REPORT_DEFINITIONS = [
  { id: '1_DAILY_MANPOWER', name: '1. Daily Manpower Report (Parade State)' },
  { id: '2_DAILY_DUTY', name: '2. Daily Duty Detail Roster' },
  { id: '3_WEEKLY_DUTY', name: '3. Weekly Duty Analysis Report' },
  { id: '4_MONTHLY_DUTY', name: '4. Monthly Duty Analysis & Fatigue Report' },
  { id: '5_NIGHT_DUTY', name: '5. Night Duty (22:00-06:00) Report' },
  { id: '6_FATIGUE_INDEX', name: '6. Fatigue Index & Workload Report' },
  { id: '7_PT_ATTENDANCE', name: '7. Physical Training (PT) Attendance Report' },
  { id: '8_GAMES_ATTENDANCE', name: '8. Evening Games Attendance Report' },
  { id: '9_COMBINED_PERFORMANCE', name: '9. Combined Duty, PT & Games Report' },
  { id: '10_CURRENT_LEAVE_STATUS', name: '10. Current Leave Status & Absence Roll' },
  { id: '11_YEARLY_LEAVE_SUMMARY', name: '11. Annual Leave Summary & Balance' },
  { id: '12_C_LEAVE_DUE', name: '12. C Leave Due in 15 Days Nominal Roll' },
  { id: '13_C_LEAVE_OVERDUE', name: '13. C Leave Overdue Nominal Roll' },
  { id: '14_LEAVE_FORECAST_3M', name: '14. 3-Month Forward C Leave Forecast' },
  { id: '15_INDIVIDUAL_DOSSIER', name: '15. Individual Confidential Dossier' },
  { id: '16_TRADE_MANPOWER', name: '16. Trade-wise Master Manpower Breakdown' },
];

export const ReportsView: React.FC = () => {
  const { success, error } = useToast();
  const [selectedReport, setSelectedReport] = useState('1_DAILY_MANPOWER');
  const [reportDate, setReportDate] = useState(format(new Date(), 'yyyy-MM-dd'));
  const [selectedYear, setSelectedYear] = useState<number>(new Date().getFullYear());
  const [selectedMonth, setSelectedMonth] = useState(format(new Date(), 'yyyy-MM'));
  const [selectedDutyType, setSelectedDutyType] = useState('');
  const [selectedLeaveType, setSelectedLeaveType] = useState('');
  const [selectedTrade, setSelectedTrade] = useState('');

  const [personnelList, setPersonnelList] = useState<any[]>([]);
  const [selectedPersonnelId, setSelectedPersonnelId] = useState('');
  const [reportData, setReportData] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);

  useEffect(() => {
    api.getPersonnel({ isActive: true }).then((res) => {
      setPersonnelList(res.personnel || []);
      if (res.personnel && res.personnel.length > 0 && !selectedPersonnelId) {
        setSelectedPersonnelId(res.personnel[0].id);
      }
    }).catch((e) => console.error(e));
  }, []);

  const fetchReport = async () => {
    setIsLoading(true);
    setFetchError(null);
    try {
      const res = await api.generateReport({
        reportType: selectedReport,
        date: reportDate,
        year: selectedYear,
        month: selectedMonth,
        personnelId: selectedPersonnelId,
        dutyType: selectedDutyType,
        leaveType: selectedLeaveType,
        trade: selectedTrade,
      });
      setReportData(res);
    } catch (e: any) {
      console.error(e);
      setFetchError(e.message || 'Failed to fetch report from database.');
      error('Report Generation Error', e.message);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchReport();
  }, [
    selectedReport,
    reportDate,
    selectedYear,
    selectedMonth,
    selectedPersonnelId,
    selectedDutyType,
    selectedLeaveType,
    selectedTrade,
  ]);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    if (!reportData) return;
    try {
      const doc = new jsPDF();
      doc.setFontSize(14);
      doc.text('UNITPULSE', 105, 15, { align: 'center' });
      doc.setFontSize(12);
      doc.text('55 Fd Amb (10 Inf Div)', 105, 22, { align: 'center' });
      doc.setFontSize(11);
      doc.text(`Report Name: ${reportData.title}`, 105, 29, { align: 'center' });
      doc.setFontSize(9);
      doc.text(`Generated Date: ${reportData.metadata?.generatedAt || format(new Date(), 'dd MMM yyyy HH:mm')}`, 14, 37);
      doc.text(`Generated By: ${reportData.metadata?.generatedBy || '2IC'}`, 196, 37, { align: 'right' });

      // Build table based on report
      let head: string[][] = [];
      let body: any[][] = [];

      const d = reportData.data || {};

      if (d.personnelList) {
        head = [['Ser', 'Army No', 'Rank & Name', 'Trade', 'Appointment', 'Status', 'Reason / Location']];
        body = d.personnelList.map((p: any, i: number) => [
          i + 1,
          p.armyNumber,
          `${p.rank} ${p.name}`,
          p.trade,
          p.appointment,
          p.status,
          p.reason,
        ]);
      } else if (d.duties) {
        head = [['Ser', 'Duty Detail', 'Army No', 'Rank & Name', 'Trade', 'Location', 'Timings', 'Duration', 'Status']];
        body = d.duties.map((du: any, i: number) => [
          i + 1,
          du.duty_type,
          du.army_number,
          `${du.rank} ${du.name}`,
          du.trade,
          du.location,
          `${du.start_time} - ${du.end_time}`,
          `${du.duration_hours}h`,
          du.activeStatus || 'SCHEDULED',
        ]);
      } else if (d.soldierStats) {
        head = [['Ser', 'Army No', 'Rank & Name', 'Trade', 'Duty Count', 'Duty %', 'Total Hours', 'Night Duties']];
        body = d.soldierStats.map((s: any, i: number) => [
          i + 1,
          s.armyNumber,
          `${s.rank} ${s.name}`,
          s.trade,
          s.dutyCount,
          `${s.dutyPercentage}%`,
          `${s.dutyHours}h`,
          s.nightDuties,
        ]);
      } else if (d.nightDuties) {
        head = [['Ser', 'Date', 'Duty Detail', 'Army No', 'Rank & Name', 'Trade', 'Timings', 'Night Hours']];
        body = d.nightDuties.map((nd: any, i: number) => [
          i + 1,
          nd.date,
          nd.duty_type,
          nd.army_number,
          `${nd.rank} ${nd.name}`,
          nd.trade,
          `${nd.start_time} - ${nd.end_time}`,
          `${nd.night_duty_hours}h`,
        ]);
      } else if (d.fatigueList) {
        head = [['Ser', 'Army No', 'Rank & Name', 'Trade', 'Duties', 'Hours', 'Night Duties', 'Night Hours', 'Score', 'Fatigue']];
        body = d.fatigueList.map((f: any, i: number) => [
          i + 1,
          f.armyNumber,
          `${f.rank} ${f.name}`,
          f.trade,
          f.dutyCount,
          `${f.dutyHours}h`,
          f.nightDuties,
          `${f.nightDutyHours}h`,
          f.fatigueScore,
          f.fatigueLevel,
        ]);
      } else if (d.ptList) {
        head = [['Ser', 'Army No', 'Rank & Name', 'Trade', 'Sessions', 'Attended', 'Excused', 'Missed', 'PT %']];
        body = d.ptList.map((pt: any, i: number) => [
          i + 1,
          pt.armyNumber,
          `${pt.rank} ${pt.name}`,
          pt.trade,
          pt.totalSessions,
          pt.attended,
          pt.excusedDuty + pt.excusedMed,
          pt.missed,
          `${pt.percentage}%`,
        ]);
      } else if (d.gamesList) {
        head = [['Ser', 'Army No', 'Rank & Name', 'Trade', 'Sessions', 'Attended', 'Excused', 'Missed', 'Games %']];
        body = d.gamesList.map((gm: any, i: number) => [
          i + 1,
          gm.armyNumber,
          `${gm.rank} ${gm.name}`,
          gm.trade,
          gm.totalSessions,
          gm.attended,
          gm.excusedDuty + gm.excusedMed,
          gm.missed,
          `${gm.percentage}%`,
        ]);
      } else if (d.combined) {
        head = [['Ser', 'Army No', 'Rank & Name', 'Trade', 'Duties', 'Duty %', 'Duty Hours', 'Night Duties', 'PT %', 'Games %', 'Leave Days']];
        body = d.combined.map((c: any, i: number) => [
          i + 1,
          c.armyNumber,
          `${c.rank} ${c.name}`,
          c.trade,
          c.dutyDays,
          `${c.dutyPercentage}%`,
          `${c.dutyHours}h`,
          c.nightDuties,
          `${c.ptPct}%`,
          `${c.gmPct}%`,
          `${c.leaveDays}d`,
        ]);
      } else if (d.activeLeaves) {
        head = [['Ser', 'Army No', 'Rank & Name', 'Trade', 'Category', 'Start Date', 'End Date', 'Days', 'Destination']];
        body = d.activeLeaves.map((al: any, i: number) => [
          i + 1,
          al.army_number,
          `${al.rank} ${al.name}`,
          al.trade,
          al.leave_type,
          al.start_date,
          al.end_date,
          `${al.total_days}d`,
          al.destination_address || '-',
        ]);
      } else if (d.summary) {
        head = [['Ser', 'Army No', 'Rank & Name', 'Trade', 'P-Limit', 'P-Used', 'P-Remain', 'C-Days', 'Total Away']];
        body = d.summary.map((s: any, i: number) => [
          i + 1,
          s.armyNumber,
          `${s.rank} ${s.name}`,
          s.trade,
          `${s.pLeaveLimit}d`,
          `${s.pLeaveUsed}d`,
          `${s.pLeaveRemaining}d`,
          `${s.cLeaveDays}d`,
          `${s.totalDaysAway}d`,
        ]);
      } else if (d.dueList) {
        head = [['Ser', 'Army No', 'Rank & Name', 'Trade', 'Last Leave Date', 'Expected Due Date', 'Days Until Due']];
        body = d.dueList.map((dl: any, i: number) => [
          i + 1,
          dl.armyNumber,
          `${dl.rank} ${dl.name}`,
          dl.trade,
          dl.lastLeaveDate,
          dl.dueDate,
          `In ${dl.daysUntilDue} days`,
        ]);
      } else if (d.overdueList) {
        head = [['Ser', 'Army No', 'Rank & Name', 'Trade', 'Last Leave Date', 'Expected Due Date', 'Days Overdue']];
        body = d.overdueList.map((ol: any, i: number) => [
          i + 1,
          ol.armyNumber,
          `${ol.rank} ${ol.name}`,
          ol.trade,
          ol.lastLeaveDate,
          ol.dueDate,
          `+${ol.daysOverdue} days`,
        ]);
      } else if (d.forecast) {
        head = [['Ser', 'Target Month', 'Army No', 'Rank & Name', 'Trade', 'Last Leave Date', 'Expected Due Date']];
        body = d.forecast.map((fc: any, i: number) => [
          i + 1,
          fc.targetMonth,
          fc.armyNumber,
          `${fc.rank} ${fc.name}`,
          fc.trade,
          fc.lastLeaveDate,
          fc.expectedDueDate,
        ]);
      } else if (d.soldier) {
        head = [['Category', 'Details']];
        body = [
          ['Army Number', d.soldier.army_number],
          ['Rank & Name', `${d.soldier.rank} ${d.soldier.name}`],
          ['Trade & Appt', `${d.soldier.trade} (${d.soldier.appointment})`],
          ['Current Status', d.soldier.current_status],
          ['P Leave Balance', `${d.pLeaveUsed}d used / ${d.pLeaveRemaining}d left (Cap: ${d.pLeaveLimit}d)`],
          ['Duties Logged', `${d.dutySummary?.totalDuties || 0} (${d.dutySummary?.totalHours || 0}h)`],
          ['PT Attendance', `${d.ptScore?.percentage || 100}% (${d.ptScore?.attended || 0} attended)`],
          ['Games Attendance', `${d.gamesScore?.percentage || 100}% (${d.gamesScore?.attended || 0} attended)`],
        ];
      } else if (d.tradeMatrix) {
        head = [['Ser', 'Trade Specialization', 'Authorized', 'Held', 'Present', 'Absent', 'Surplus', '%']];
        body = d.tradeMatrix.map((t: any, i: number) => [
          i + 1,
          t.trade,
          t.authorized,
          t.held,
          t.present,
          t.absent !== undefined ? t.absent : (t.held - t.present),
          t.surplus !== undefined ? t.surplus : Math.max(0, t.held - t.authorized),
          `${t.percentage}%`,
        ]);
      }

      if (head.length > 0) {
        autoTable(doc, {
          startY: 42,
          head,
          body,
          theme: 'grid',
          headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255] },
          styles: { fontSize: 8, cellPadding: 2 },
        });
      }

      const filename = `${reportData.title.replace(/[^a-zA-Z0-9]/g, '_')}_${reportDate}.pdf`;
      doc.save(filename);
      success('PDF Exported', `Saved ${filename}`);
    } catch (err: any) {
      error('PDF Generation Failed', err.message);
    }
  };

  const handleExportExcel = () => {
    if (!reportData) return;
    try {
      const wb = XLSX.utils.book_new();
      let exportRows: any[] = [];
      const d = reportData.data || {};

      if (d.personnelList) exportRows = d.personnelList;
      else if (d.duties) exportRows = d.duties;
      else if (d.soldierStats) exportRows = d.soldierStats;
      else if (d.nightDuties) exportRows = d.nightDuties;
      else if (d.fatigueList) exportRows = d.fatigueList;
      else if (d.ptList) exportRows = d.ptList;
      else if (d.gamesList) exportRows = d.gamesList;
      else if (d.combined) exportRows = d.combined;
      else if (d.activeLeaves) exportRows = d.activeLeaves;
      else if (d.summary) exportRows = d.summary;
      else if (d.dueList) exportRows = d.dueList;
      else if (d.overdueList) exportRows = d.overdueList;
      else if (d.forecast) exportRows = d.forecast;
      else if (d.soldier) {
        exportRows = [{
          armyNumber: d.soldier.army_number,
          rank: d.soldier.rank,
          name: d.soldier.name,
          trade: d.soldier.trade,
          appointment: d.soldier.appointment,
          status: d.soldier.current_status,
          pLeaveLimit: d.pLeaveLimit,
          pLeaveUsed: d.pLeaveUsed,
          pLeaveRemaining: d.pLeaveRemaining,
          dutyCount: d.dutySummary?.totalDuties,
          dutyHours: d.dutySummary?.totalHours,
          ptPct: d.ptScore?.percentage,
          gamesPct: d.gamesScore?.percentage,
        }];
      } else if (d.tradeMatrix) exportRows = d.tradeMatrix;
      else exportRows = [d];

      const ws = XLSX.utils.json_to_sheet(exportRows);
      XLSX.utils.book_append_sheet(wb, ws, 'Report');
      const filename = `${reportData.title.replace(/[^a-zA-Z0-9]/g, '_')}_${reportDate}.xlsx`;
      XLSX.writeFile(wb, filename);
      success('Excel Downloaded', `Saved ${filename}`);
    } catch (err: any) {
      error('Export Failed', err.message);
    }
  };

  const d = reportData?.data || {};

  return (
    <div className="space-y-6">
      {/* Top Controls Bar (Hidden on print) */}
      <div className="print:hidden space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h2 className="text-xl sm:text-2xl font-black text-white tracking-wide flex items-center gap-2">
              <FileText className="w-6 h-6 text-army-400" />
              16 Official Military Reports & Decision Sheets
            </h2>
            <p className="text-xs text-slate-400 mt-0.5">
              Unit: <strong>{UNIT_NAME}</strong> • 100% Live Database Computations, PDF Export, Excel Export & Military Print
            </p>
          </div>

          {/* Action Buttons: VIEW REPORT, DOWNLOAD PDF, DOWNLOAD EXCEL, PRINT */}
          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={fetchReport}
              className="px-3.5 py-2 rounded-xl bg-tactical-800 hover:bg-tactical-700 text-slate-200 border border-slate-700 text-xs font-bold transition-all flex items-center space-x-1.5 shadow-sm"
            >
              <Eye className="w-3.5 h-3.5 text-emerald-400" />
              <span>View Report</span>
            </button>
            <button
              onClick={handleDownloadPDF}
              className="px-3.5 py-2 rounded-xl bg-tactical-800 hover:bg-tactical-700 text-slate-200 border border-slate-700 text-xs font-bold transition-all flex items-center space-x-1.5 shadow-sm"
            >
              <Download className="w-3.5 h-3.5 text-blue-400" />
              <span>Download PDF</span>
            </button>
            <button
              onClick={handleExportExcel}
              className="px-3.5 py-2 rounded-xl bg-tactical-800 hover:bg-tactical-700 text-slate-200 border border-slate-700 text-xs font-bold transition-all flex items-center space-x-1.5 shadow-sm"
            >
              <Download className="w-3.5 h-3.5 text-emerald-400" />
              <span>Download Excel</span>
            </button>
            <button
              onClick={handlePrint}
              className="px-4 py-2 rounded-xl bg-army-600 hover:bg-army-500 text-white text-xs font-bold transition-all flex items-center space-x-1.5 shadow-lg"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
          </div>
        </div>

        {/* Dynamic Filters Bar */}
        <div className="p-4 rounded-2xl bg-tactical-900 border border-slate-800 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 text-xs">
          <div className="lg:col-span-2">
            <label className="block text-slate-300 font-bold uppercase tracking-wider mb-1">
              Select Official Military Report *
            </label>
            <select
              value={selectedReport}
              onChange={(e) => setSelectedReport(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-tactical-950 border border-slate-700 text-white font-bold"
            >
              {REPORT_DEFINITIONS.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.name}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-slate-300 font-bold uppercase tracking-wider mb-1">
              Effective Date / Anchor Date
            </label>
            <input
              type="date"
              value={reportDate}
              onChange={(e) => setReportDate(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-tactical-950 border border-slate-700 text-white font-mono"
            />
          </div>

          {/* Contextual Secondary Filters */}
          {selectedReport === '15_INDIVIDUAL_DOSSIER' && (
            <div>
              <label className="block text-slate-300 font-bold uppercase tracking-wider mb-1">
                Select Soldier *
              </label>
              <select
                value={selectedPersonnelId}
                onChange={(e) => setSelectedPersonnelId(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-tactical-950 border border-slate-700 text-white font-semibold"
              >
                {personnelList.map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.rank} {p.name} ({p.armyNumber})
                  </option>
                ))}
              </select>
            </div>
          )}

          {['4_MONTHLY_DUTY', '14_LEAVE_FORECAST_3M'].includes(selectedReport) && (
            <div>
              <label className="block text-slate-300 font-bold uppercase tracking-wider mb-1">
                Select Month
              </label>
              <input
                type="month"
                value={selectedMonth}
                onChange={(e) => setSelectedMonth(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-tactical-950 border border-slate-700 text-white font-mono"
              />
            </div>
          )}

          {selectedReport === '11_YEARLY_LEAVE_SUMMARY' && (
            <div>
              <label className="block text-slate-300 font-bold uppercase tracking-wider mb-1">
                Select Calendar Year
              </label>
              <select
                value={selectedYear}
                onChange={(e) => setSelectedYear(parseInt(e.target.value, 10))}
                className="w-full px-3 py-2 rounded-xl bg-tactical-950 border border-slate-700 text-white font-mono"
              >
                <option value={2026}>2026</option>
                <option value={2025}>2025</option>
                <option value={2024}>2024</option>
              </select>
            </div>
          )}

          {selectedReport === '2_DAILY_DUTY' && (
            <div>
              <label className="block text-slate-300 font-bold uppercase tracking-wider mb-1">
                Filter Duty Type
              </label>
              <select
                value={selectedDutyType}
                onChange={(e) => setSelectedDutyType(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-tactical-950 border border-slate-700 text-white"
              >
                <option value="">All Duty Types</option>
                {DUTY_TYPES.map((dt) => (
                  <option key={dt} value={dt}>{dt}</option>
                ))}
              </select>
            </div>
          )}

          {selectedReport === '10_CURRENT_LEAVE_STATUS' && (
            <div>
              <label className="block text-slate-300 font-bold uppercase tracking-wider mb-1">
                Filter Leave Category
              </label>
              <select
                value={selectedLeaveType}
                onChange={(e) => setSelectedLeaveType(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-tactical-950 border border-slate-700 text-white"
              >
                <option value="">All Leave Categories</option>
                {LEAVE_TYPES.map((lt) => (
                  <option key={lt.type} value={lt.type}>{lt.label}</option>
                ))}
              </select>
            </div>
          )}

          {selectedReport === '1_DAILY_MANPOWER' && (
            <div>
              <label className="block text-slate-300 font-bold uppercase tracking-wider mb-1">
                Filter Trade
              </label>
              <select
                value={selectedTrade}
                onChange={(e) => setSelectedTrade(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-tactical-950 border border-slate-700 text-white"
              >
                <option value="">All Trades</option>
                {TRADES.map((t) => (
                  <option key={t} value={t}>{t}</option>
                ))}
              </select>
            </div>
          )}
        </div>
      </div>

      {/* Official Military Print Document Layout */}
      <div className="rounded-2xl bg-white text-slate-900 p-8 sm:p-12 shadow-2xl font-serif space-y-6 print:p-0 print:shadow-none print:m-0 print:w-full">
        {/* Exact Header Requested: UNITPULSE, 55 Fd Amb (10 Inf Div), Report Name */}
        <div className="border-b-2 border-slate-900 pb-4 text-center space-y-1">
          <div className="text-[11px] uppercase tracking-widest font-mono font-bold text-slate-600">
            CONFIDENTIAL - MILITARY HEADQUARTERS DISSEMINATION
          </div>
          <h1 className="text-2xl sm:text-3xl font-black tracking-wider uppercase font-sans text-slate-950">
            UNITPULSE
          </h1>
          <h2 className="text-base sm:text-lg font-bold font-mono text-slate-800">
            55 Fd Amb (10 Inf Div)
          </h2>
          <div className="pt-2">
            <div className="text-xs font-mono font-bold text-slate-500 uppercase">Report Name:</div>
            <h3 className="text-lg sm:text-xl font-black uppercase underline decoration-2 underline-offset-4 tracking-wide font-sans text-slate-900">
              {reportData?.title || 'MILITARY OPERATIONAL REPORT'}
            </h3>
          </div>
        </div>

        {/* Reference & Metadata Bar */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center text-xs font-mono border-b border-slate-300 pb-2 gap-1">
          <div>
            <span>Ref No: <strong>{reportData?.metadata?.referenceNo || '55FA/ADMIN/2026/01'}</strong></span>
          </div>
          <div className="text-right">
            <span>Generated Date: <strong>{reportData?.metadata?.generatedAt || format(new Date(), 'dd MMM yyyy HH:mm')}</strong></span>
            <span className="mx-2">•</span>
            <span>Generated By: <strong>{reportData?.metadata?.generatedBy || 'Duty Officer'}</strong></span>
          </div>
        </div>

        {/* Dynamic Report Content Table */}
        <div className="py-2">
          {isLoading ? (
            <div className="py-16 text-center text-slate-500 font-mono text-xs">
              <RefreshCw className="w-6 h-6 animate-spin mx-auto text-slate-600 mb-2" />
              <span>Querying central database & calculating report parameters...</span>
            </div>
          ) : fetchError ? (
            <div className="p-8 text-center bg-rose-50 border border-rose-200 rounded-xl space-y-3">
              <AlertTriangle className="w-8 h-8 text-rose-500 mx-auto" />
              <div className="text-sm font-bold text-rose-800">Error Generating Report</div>
              <p className="text-xs text-rose-600 font-mono">{fetchError}</p>
              <button
                onClick={fetchReport}
                className="px-4 py-1.5 bg-rose-600 text-white text-xs font-bold rounded-lg hover:bg-rose-500 shadow"
              >
                Retry Query
              </button>
            </div>
          ) : (
            <div className="space-y-4">
              {/* 1. DAILY MANPOWER REPORT */}
              {selectedReport === '1_DAILY_MANPOWER' && (
                <div className="space-y-4">
                  <div className="grid grid-cols-3 sm:grid-cols-6 gap-2 text-center text-xs font-mono border border-slate-900 p-2.5 bg-slate-100 font-bold">
                    <div>Authorized: <span className="text-slate-900">{d.statusCounts?.authorized ?? 120}</span></div>
                    <div>Held: <span className="text-blue-800">{d.statusCounts?.held ?? 0}</span></div>
                    <div>Present: <span className="text-emerald-800">{d.statusCounts?.present ?? 0}</span></div>
                    <div>Absent: <span className="text-amber-800">{d.statusCounts?.absent ?? 0}</span></div>
                    <div>Surplus: <span className="text-purple-800">{d.statusCounts?.surplus ?? 0}</span></div>
                    <div>Percentage: <span className="text-slate-900">{d.statusCounts?.percentage ?? 0}%</span></div>
                  </div>

                  <div className="grid grid-cols-2 sm:grid-cols-6 gap-1 text-[11px] font-mono p-2 bg-slate-50 border border-slate-300">
                    <div>Leave: <strong>{d.statusCounts?.leave ?? 0}</strong></div>
                    <div>Course: <strong>{d.statusCounts?.course ?? 0}</strong></div>
                    <div>TY Duty: <strong>{d.statusCounts?.tyDuty ?? 0}</strong></div>
                    <div>Attachment: <strong>{d.statusCounts?.attachment ?? 0}</strong></div>
                    <div>Hospital: <strong>{d.statusCounts?.hospital ?? 0}</strong></div>
                    <div>Other: <strong>{d.statusCounts?.other ?? 0}</strong></div>
                  </div>

                  <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                    <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                      <tr>
                        <th className="p-2 border border-slate-400 text-center">Ser</th>
                        <th className="p-2 border border-slate-400">Army No</th>
                        <th className="p-2 border border-slate-400">Rank & Name</th>
                        <th className="p-2 border border-slate-400">Trade</th>
                        <th className="p-2 border border-slate-400">Appointment</th>
                        <th className="p-2 border border-slate-400">Status</th>
                        <th className="p-2 border border-slate-400">Reason / Location</th>
                      </tr>
                    </thead>
                    <tbody>
                      {!d.personnelList || d.personnelList.length === 0 ? (
                        <tr><td colSpan={7} className="p-6 text-center text-slate-500 font-mono">No personnel records found.</td></tr>
                      ) : (
                        d.personnelList.map((p: any, i: number) => (
                          <tr key={i} className="border-b border-slate-300">
                            <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                            <td className="p-2 border border-slate-300 font-mono font-bold">{p.armyNumber}</td>
                            <td className="p-2 border border-slate-300 font-bold">{p.rank} {p.name}</td>
                            <td className="p-2 border border-slate-300 font-mono">{p.trade}</td>
                            <td className="p-2 border border-slate-300">{p.appointment}</td>
                            <td className="p-2 border border-slate-300 font-mono font-bold">{p.status}</td>
                            <td className="p-2 border border-slate-300 text-slate-700">{p.reason}</td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              )}

              {/* 2. DAILY DUTY DETAIL ROSTER */}
              {selectedReport === '2_DAILY_DUTY' && (
                <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                  <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                    <tr>
                      <th className="p-2 border border-slate-400 text-center">Ser</th>
                      <th className="p-2 border border-slate-400">Duty Detail</th>
                      <th className="p-2 border border-slate-400">Army No</th>
                      <th className="p-2 border border-slate-400">Rank & Name</th>
                      <th className="p-2 border border-slate-400">Trade</th>
                      <th className="p-2 border border-slate-400">Location</th>
                      <th className="p-2 border border-slate-400">Timings</th>
                      <th className="p-2 border border-slate-400 text-center">Duration</th>
                      <th className="p-2 border border-slate-400">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {!d.duties || d.duties.length === 0 ? (
                      <tr><td colSpan={9} className="p-6 text-center text-slate-500">No duties assigned for {reportDate}</td></tr>
                    ) : (
                      d.duties.map((du: any, i: number) => (
                        <tr key={i} className="border-b border-slate-300">
                          <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                          <td className="p-2 border border-slate-300 font-bold">{du.duty_type}</td>
                          <td className="p-2 border border-slate-300 font-mono">{du.army_number}</td>
                          <td className="p-2 border border-slate-300 font-bold">{du.rank} {du.name}</td>
                          <td className="p-2 border border-slate-300 font-mono">{du.trade}</td>
                          <td className="p-2 border border-slate-300">{du.location}</td>
                          <td className="p-2 border border-slate-300 font-mono">{du.start_time} - {du.end_time}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold">{du.duration_hours}h</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold">{du.activeStatus}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              )}

              {/* 3 & 4. WEEKLY & MONTHLY DUTY ANALYSIS */}
              {['3_WEEKLY_DUTY', '4_MONTHLY_DUTY'].includes(selectedReport) && (
                <div className="space-y-4">
                  <div className="grid grid-cols-4 gap-2 text-center text-xs font-mono border border-slate-900 p-2 bg-slate-100 font-bold">
                    <div>Total Duties: {d.totalDuties || 0}</div>
                    <div>Total Active Hours: {d.totalHours || 0}h</div>
                    <div>Night Duties (22-06): {d.totalNightDuties || d.nightDuties || 0}</div>
                    <div>Night Hours: {d.totalNightHours || 0}h</div>
                  </div>

                  <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                    <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                      <tr>
                        <th className="p-2 border border-slate-400 text-center">Ser</th>
                        <th className="p-2 border border-slate-400">Army No</th>
                        <th className="p-2 border border-slate-400">Rank & Name</th>
                        <th className="p-2 border border-slate-400">Trade</th>
                        <th className="p-2 border border-slate-400 text-center">Total Duties</th>
                        <th className="p-2 border border-slate-400 text-center">Duty %</th>
                        <th className="p-2 border border-slate-400 text-center">Active Hours</th>
                        <th className="p-2 border border-slate-400 text-center">Night Duties</th>
                      </tr>
                    </thead>
                    <tbody>
                      {!d.soldierStats || d.soldierStats.length === 0 ? (
                        <tr><td colSpan={8} className="p-6 text-center text-slate-500 font-mono">No soldier statistics available for selected range.</td></tr>
                      ) : (
                        d.soldierStats.map((s: any, i: number) => (
                          <tr key={i} className="border-b border-slate-300">
                            <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                            <td className="p-2 border border-slate-300 font-mono font-bold">{s.armyNumber}</td>
                            <td className="p-2 border border-slate-300 font-bold">{s.rank} {s.name}</td>
                            <td className="p-2 border border-slate-300 font-mono">{s.trade}</td>
                            <td className="p-2 border border-slate-300 font-mono text-center font-bold">{s.dutyCount}</td>
                            <td className="p-2 border border-slate-300 font-mono text-center">{s.dutyPercentage}%</td>
                            <td className="p-2 border border-slate-300 font-mono text-center">{s.dutyHours}h</td>
                            <td className="p-2 border border-slate-300 font-mono text-center font-bold text-purple-900">{s.nightDuties}</td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              )}

              {/* 5. NIGHT DUTY REPORT */}
              {selectedReport === '5_NIGHT_DUTY' && (
                <div className="space-y-4">
                  <div className="p-2 bg-purple-50 border border-purple-300 font-mono text-xs font-bold flex justify-between">
                    <span>Total Night Shifts (22:00-06:00): {d.totalNightDuties || 0}</span>
                    <span>Cumulative Night Hours: {d.totalNightHours || 0}h</span>
                  </div>

                  <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                    <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                      <tr>
                        <th className="p-2 border border-slate-400 text-center">Ser</th>
                        <th className="p-2 border border-slate-400">Date</th>
                        <th className="p-2 border border-slate-400">Duty Detail</th>
                        <th className="p-2 border border-slate-400">Army No</th>
                        <th className="p-2 border border-slate-400">Rank & Name</th>
                        <th className="p-2 border border-slate-400">Trade</th>
                        <th className="p-2 border border-slate-400">Timings</th>
                        <th className="p-2 border border-slate-400 text-center">Night Hours</th>
                      </tr>
                    </thead>
                    <tbody>
                      {!d.nightDuties || d.nightDuties.length === 0 ? (
                        <tr><td colSpan={8} className="p-6 text-center text-slate-500 font-mono">No night duties logged during this window.</td></tr>
                      ) : (
                        d.nightDuties.map((nd: any, i: number) => (
                          <tr key={i} className="border-b border-slate-300">
                            <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                            <td className="p-2 border border-slate-300 font-mono">{nd.date}</td>
                            <td className="p-2 border border-slate-300 font-bold">{nd.duty_type}</td>
                            <td className="p-2 border border-slate-300 font-mono">{nd.army_number}</td>
                            <td className="p-2 border border-slate-300 font-bold">{nd.rank} {nd.name}</td>
                            <td className="p-2 border border-slate-300 font-mono">{nd.trade}</td>
                            <td className="p-2 border border-slate-300 font-mono">{nd.start_time} - {nd.end_time}</td>
                            <td className="p-2 border border-slate-300 font-mono text-center font-bold text-purple-900">{nd.night_duty_hours}h</td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              )}

              {/* 6. FATIGUE INDEX REPORT */}
              {selectedReport === '6_FATIGUE_INDEX' && (
                <div className="space-y-4">
                  <div className="grid grid-cols-3 gap-2 text-center text-xs font-mono border border-slate-900 p-2 bg-slate-100 font-bold">
                    <div className="text-emerald-800">Low Fatigue: {d.summary?.low || 0} Soldiers</div>
                    <div className="text-amber-800">Moderate Fatigue: {d.summary?.moderate || 0} Soldiers</div>
                    <div className="text-rose-800">High Fatigue: {d.summary?.high || 0} Soldiers</div>
                  </div>

                  <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                    <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                      <tr>
                        <th className="p-2 border border-slate-400 text-center">Ser</th>
                        <th className="p-2 border border-slate-400">Army No</th>
                        <th className="p-2 border border-slate-400">Rank & Name</th>
                        <th className="p-2 border border-slate-400">Trade</th>
                        <th className="p-2 border border-slate-400 text-center">Total Duties</th>
                        <th className="p-2 border border-slate-400 text-center">Hours</th>
                        <th className="p-2 border border-slate-400 text-center">Night Duties</th>
                        <th className="p-2 border border-slate-400 text-center">Night Hours</th>
                        <th className="p-2 border border-slate-400 text-center">Fatigue Score</th>
                        <th className="p-2 border border-slate-400 text-center">Fatigue Level</th>
                      </tr>
                    </thead>
                    <tbody>
                      {!d.fatigueList || d.fatigueList.length === 0 ? (
                        <tr><td colSpan={10} className="p-6 text-center text-slate-500 font-mono">No fatigue index data available.</td></tr>
                      ) : (
                        d.fatigueList.map((f: any, i: number) => (
                          <tr key={i} className="border-b border-slate-300">
                            <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                            <td className="p-2 border border-slate-300 font-mono font-bold">{f.armyNumber}</td>
                            <td className="p-2 border border-slate-300 font-bold">{f.rank} {f.name}</td>
                            <td className="p-2 border border-slate-300 font-mono">{f.trade}</td>
                            <td className="p-2 border border-slate-300 font-mono text-center">{f.dutyCount}</td>
                            <td className="p-2 border border-slate-300 font-mono text-center">{f.dutyHours}h</td>
                            <td className="p-2 border border-slate-300 font-mono text-center">{f.nightDuties}</td>
                            <td className="p-2 border border-slate-300 font-mono text-center">{f.nightDutyHours}h</td>
                            <td className="p-2 border border-slate-300 font-mono text-center font-bold">{f.fatigueScore}</td>
                            <td className="p-2 border border-slate-300 font-mono text-center font-bold">{f.fatigueLevel}</td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              )}

              {/* 7 & 8. PT & GAMES ATTENDANCE REPORTS */}
              {['7_PT_ATTENDANCE', '8_GAMES_ATTENDANCE'].includes(selectedReport) && (
                <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                  <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                    <tr>
                      <th className="p-2 border border-slate-400 text-center">Ser</th>
                      <th className="p-2 border border-slate-400">Army No</th>
                      <th className="p-2 border border-slate-400">Rank & Name</th>
                      <th className="p-2 border border-slate-400">Trade</th>
                      <th className="p-2 border border-slate-400 text-center">Total Sessions</th>
                      <th className="p-2 border border-slate-400 text-center">Attended</th>
                      <th className="p-2 border border-slate-400 text-center">Excused (Duty/Med)</th>
                      <th className="p-2 border border-slate-400 text-center">Unexcused Missed</th>
                      <th className="p-2 border border-slate-400 text-center">Attendance %</th>
                    </tr>
                  </thead>
                  <tbody>
                    {!(d.ptList || d.gamesList) || (d.ptList || d.gamesList).length === 0 ? (
                      <tr><td colSpan={9} className="p-6 text-center text-slate-500 font-mono">No attendance entries recorded.</td></tr>
                    ) : (
                      (d.ptList || d.gamesList).map((row: any, i: number) => (
                        <tr key={i} className="border-b border-slate-300">
                          <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold">{row.armyNumber}</td>
                          <td className="p-2 border border-slate-300 font-bold">{row.rank} {row.name}</td>
                          <td className="p-2 border border-slate-300 font-mono">{row.trade}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center">{row.totalSessions}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold text-emerald-800">{row.attended}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center">{row.excusedDuty + row.excusedMed}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold text-rose-800">{row.missed}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold">{row.percentage}%</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              )}

              {/* 9. COMBINED DUTY/PT/GAMES REPORT */}
              {selectedReport === '9_COMBINED_PERFORMANCE' && (
                <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                  <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                    <tr>
                      <th className="p-2 border border-slate-400 text-center">Ser</th>
                      <th className="p-2 border border-slate-400">Army No</th>
                      <th className="p-2 border border-slate-400">Rank & Name</th>
                      <th className="p-2 border border-slate-400">Trade</th>
                      <th className="p-2 border border-slate-400 text-center">Duties</th>
                      <th className="p-2 border border-slate-400 text-center">Duty %</th>
                      <th className="p-2 border border-slate-400 text-center">Duty Hours</th>
                      <th className="p-2 border border-slate-400 text-center">Night Duties</th>
                      <th className="p-2 border border-slate-400 text-center">PT %</th>
                      <th className="p-2 border border-slate-400 text-center">Games %</th>
                      <th className="p-2 border border-slate-400 text-center">Leave Days</th>
                    </tr>
                  </thead>
                  <tbody>
                    {!d.combined || d.combined.length === 0 ? (
                      <tr><td colSpan={11} className="p-6 text-center text-slate-500 font-mono">No combined correlation metrics found.</td></tr>
                    ) : (
                      d.combined.map((c: any, i: number) => (
                        <tr key={i} className="border-b border-slate-300">
                          <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold">{c.armyNumber}</td>
                          <td className="p-2 border border-slate-300 font-bold">{c.rank} {c.name}</td>
                          <td className="p-2 border border-slate-300 font-mono">{c.trade}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold">{c.dutyDays}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center">{c.dutyPercentage}%</td>
                          <td className="p-2 border border-slate-300 font-mono text-center">{c.dutyHours}h</td>
                          <td className="p-2 border border-slate-300 font-mono text-center text-purple-900 font-bold">{c.nightDuties}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold text-emerald-800">{c.ptPct}%</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold text-blue-800">{c.gmPct}%</td>
                          <td className="p-2 border border-slate-300 font-mono text-center">{c.leaveDays}d</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              )}

              {/* 10. CURRENT LEAVE STATUS */}
              {selectedReport === '10_CURRENT_LEAVE_STATUS' && (
                <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                  <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                    <tr>
                      <th className="p-2 border border-slate-400 text-center">Ser</th>
                      <th className="p-2 border border-slate-400">Army No</th>
                      <th className="p-2 border border-slate-400">Rank & Name</th>
                      <th className="p-2 border border-slate-400">Trade</th>
                      <th className="p-2 border border-slate-400">Category</th>
                      <th className="p-2 border border-slate-400">Start Date</th>
                      <th className="p-2 border border-slate-400">End Date</th>
                      <th className="p-2 border border-slate-400 text-center">Days</th>
                      <th className="p-2 border border-slate-400">Destination / Contact</th>
                    </tr>
                  </thead>
                  <tbody>
                    {!d.activeLeaves || d.activeLeaves.length === 0 ? (
                      <tr><td colSpan={9} className="p-6 text-center text-slate-500">No personnel currently away on leave.</td></tr>
                    ) : (
                      d.activeLeaves.map((l: any, i: number) => (
                        <tr key={i} className="border-b border-slate-300">
                          <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold">{l.army_number}</td>
                          <td className="p-2 border border-slate-300 font-bold">{l.rank} {l.name}</td>
                          <td className="p-2 border border-slate-300 font-mono">{l.trade}</td>
                          <td className="p-2 border border-slate-300 font-bold">{l.leave_type.replace('_', ' ')}</td>
                          <td className="p-2 border border-slate-300 font-mono">{l.start_date}</td>
                          <td className="p-2 border border-slate-300 font-mono">{l.end_date}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold">{l.total_days}d</td>
                          <td className="p-2 border border-slate-300">{l.destination_address || l.emergency_contact || '-'}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              )}

              {/* 11. YEARLY LEAVE SUMMARY */}
              {selectedReport === '11_YEARLY_LEAVE_SUMMARY' && (
                <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                  <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                    <tr>
                      <th className="p-2 border border-slate-400 text-center">Ser</th>
                      <th className="p-2 border border-slate-400">Army No</th>
                      <th className="p-2 border border-slate-400">Rank & Name</th>
                      <th className="p-2 border border-slate-400">Trade</th>
                      <th className="p-2 border border-slate-400 text-center">P-Limit</th>
                      <th className="p-2 border border-slate-400 text-center">P-Used</th>
                      <th className="p-2 border border-slate-400 text-center">P-Remaining</th>
                      <th className="p-2 border border-slate-400 text-center">C-Leave Days</th>
                      <th className="p-2 border border-slate-400 text-center">Total Days Away</th>
                    </tr>
                  </thead>
                  <tbody>
                    {!d.summary || d.summary.length === 0 ? (
                      <tr><td colSpan={9} className="p-6 text-center text-slate-500 font-mono">No yearly summary data found.</td></tr>
                    ) : (
                      d.summary.map((s: any, i: number) => (
                        <tr key={i} className="border-b border-slate-300">
                          <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold">{s.armyNumber}</td>
                          <td className="p-2 border border-slate-300 font-bold">{s.rank} {s.name}</td>
                          <td className="p-2 border border-slate-300 font-mono">{s.trade}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold text-slate-800">{s.pLeaveLimit}d</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold text-blue-900">{s.pLeaveUsed}d</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold text-emerald-900">{s.pLeaveRemaining}d</td>
                          <td className="p-2 border border-slate-300 font-mono text-center">{s.cLeaveDays}d</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold">{s.totalDaysAway}d</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              )}

              {/* 12. C LEAVE DUE IN 15 DAYS */}
              {selectedReport === '12_C_LEAVE_DUE' && (
                <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                  <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                    <tr>
                      <th className="p-2 border border-slate-400 text-center">Ser</th>
                      <th className="p-2 border border-slate-400">Army No</th>
                      <th className="p-2 border border-slate-400">Rank & Name</th>
                      <th className="p-2 border border-slate-400">Trade</th>
                      <th className="p-2 border border-slate-400">Last C Leave Date</th>
                      <th className="p-2 border border-slate-400">Expected Due Date</th>
                      <th className="p-2 border border-slate-400 text-center">Days Until Due</th>
                    </tr>
                  </thead>
                  <tbody>
                    {!d.dueList || d.dueList.length === 0 ? (
                      <tr><td colSpan={7} className="p-6 text-center text-slate-500">No personnel due for C Leave within next 15 days.</td></tr>
                    ) : (
                      d.dueList.map((dl: any, i: number) => (
                        <tr key={i} className="border-b border-slate-300">
                          <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold">{dl.armyNumber}</td>
                          <td className="p-2 border border-slate-300 font-bold">{dl.rank} {dl.name}</td>
                          <td className="p-2 border border-slate-300 font-mono">{dl.trade}</td>
                          <td className="p-2 border border-slate-300 font-mono">{dl.lastLeaveDate}</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold text-amber-800">{dl.dueDate}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold text-amber-800">{dl.daysUntilDue} days</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              )}

              {/* 13. C LEAVE OVERDUE */}
              {selectedReport === '13_C_LEAVE_OVERDUE' && (
                <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                  <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                    <tr>
                      <th className="p-2 border border-slate-400 text-center">Ser</th>
                      <th className="p-2 border border-slate-400">Army No</th>
                      <th className="p-2 border border-slate-400">Rank & Name</th>
                      <th className="p-2 border border-slate-400">Trade</th>
                      <th className="p-2 border border-slate-400">Last C Leave Date</th>
                      <th className="p-2 border border-slate-400">Expected Due Date</th>
                      <th className="p-2 border border-slate-400 text-center">Days Overdue</th>
                    </tr>
                  </thead>
                  <tbody>
                    {!d.overdueList || d.overdueList.length === 0 ? (
                      <tr><td colSpan={7} className="p-6 text-center text-slate-500">No personnel currently overdue for C Leave.</td></tr>
                    ) : (
                      d.overdueList.map((ol: any, i: number) => (
                        <tr key={i} className="border-b border-slate-300">
                          <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold">{ol.armyNumber}</td>
                          <td className="p-2 border border-slate-300 font-bold">{ol.rank} {ol.name}</td>
                          <td className="p-2 border border-slate-300 font-mono">{ol.trade}</td>
                          <td className="p-2 border border-slate-300 font-mono">{ol.lastLeaveDate}</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold text-rose-800">{ol.dueDate}</td>
                          <td className="p-2 border border-slate-300 font-mono text-center font-bold text-rose-800">+{ol.daysOverdue} days</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              )}

              {/* 14. 3-MONTH FORWARD C LEAVE FORECAST */}
              {selectedReport === '14_LEAVE_FORECAST_3M' && (
                <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                  <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                    <tr>
                      <th className="p-2 border border-slate-400 text-center">Ser</th>
                      <th className="p-2 border border-slate-400">Target Month</th>
                      <th className="p-2 border border-slate-400">Army No</th>
                      <th className="p-2 border border-slate-400">Rank & Name</th>
                      <th className="p-2 border border-slate-400">Trade</th>
                      <th className="p-2 border border-slate-400">Last Leave Date</th>
                      <th className="p-2 border border-slate-400">Expected Due Date</th>
                    </tr>
                  </thead>
                  <tbody>
                    {!d.forecast || d.forecast.length === 0 ? (
                      <tr><td colSpan={7} className="p-6 text-center text-slate-500 font-mono">No C-Leave forecast entries scheduled.</td></tr>
                    ) : (
                      d.forecast.map((fc: any, i: number) => (
                        <tr key={i} className="border-b border-slate-300">
                          <td className="p-2 border border-slate-300 font-mono text-center">{i + 1}</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold">{fc.targetMonth}</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold">{fc.armyNumber}</td>
                          <td className="p-2 border border-slate-300 font-bold">{fc.rank} {fc.name}</td>
                          <td className="p-2 border border-slate-300 font-mono">{fc.trade}</td>
                          <td className="p-2 border border-slate-300 font-mono">{fc.lastLeaveDate}</td>
                          <td className="p-2 border border-slate-300 font-mono font-bold text-amber-800">{fc.expectedDueDate}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              )}

              {/* 15. INDIVIDUAL CONFIDENTIAL PERSONNEL DOSSIER */}
              {selectedReport === '15_INDIVIDUAL_DOSSIER' && (
                !d.soldier ? (
                  <div className="p-8 text-center bg-slate-50 border border-slate-200 rounded-xl space-y-2 font-mono text-xs">
                    <p className="text-slate-600 font-bold">Please select a soldier from the dropdown filter above to generate their Individual Dossier.</p>
                  </div>
                ) : (
                  <div className="space-y-4 font-sans text-xs">
                    <div className="p-4 border border-slate-900 bg-slate-50 space-y-2">
                      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 font-mono">
                        <div>Army No: <strong>{d.soldier.army_number}</strong></div>
                        <div>Rank: <strong>{d.soldier.rank}</strong></div>
                        <div>Name: <strong>{d.soldier.name}</strong></div>
                        <div>Trade: <strong>{d.soldier.trade}</strong></div>
                        <div>Appt: <strong>{d.soldier.appointment}</strong></div>
                        <div>Status: <strong>{d.soldier.current_status}</strong></div>
                        <div>P-Limit: <strong>{d.pLeaveLimit}d ({d.pLeaveRemaining}d left)</strong></div>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-center font-mono p-3 bg-slate-100 border border-slate-300">
                      <div>Duties Logged: <strong>{d.dutySummary?.totalDuties || 0} ({d.dutySummary?.totalHours || 0}h)</strong></div>
                      <div>PT Rate: <strong>{d.ptScore?.percentage || 100}% ({d.ptScore?.attended || 0} sessions)</strong></div>
                      <div>Games Rate: <strong>{d.gamesScore?.percentage || 100}% ({d.gamesScore?.attended || 0} sessions)</strong></div>
                    </div>
                  </div>
                )
              )}

              {/* 16. TRADE-WISE MASTER MANPOWER BREAKDOWN */}
              {selectedReport === '16_TRADE_MANPOWER' && (
                <div className="space-y-4">
                  <div className="grid grid-cols-5 gap-2 text-center text-xs font-mono border border-slate-900 p-2 bg-slate-100 font-bold">
                    <div>Authorized: {d.summary?.authorized || 0}</div>
                    <div>Held: {d.summary?.held || 0}</div>
                    <div>Present: {d.summary?.present || 0}</div>
                    <div>Absent: {d.summary?.absent || 0}</div>
                    <div>Surplus: {d.summary?.surplus || 0}</div>
                  </div>

                  <table className="w-full text-left text-xs border-collapse border border-slate-400 font-sans">
                    <thead className="bg-slate-200 border-b border-slate-400 font-bold font-mono text-[11px]">
                      <tr>
                        <th className="p-2 border border-slate-400 text-center">Ser</th>
                        <th className="p-2 border border-slate-400">Trade</th>
                        <th className="p-2 border border-slate-400 text-center">Authorized</th>
                        <th className="p-2 border border-slate-400 text-center">Held</th>
                        <th className="p-2 border border-slate-400 text-center">Present</th>
                        <th className="p-2 border border-slate-400 text-center">Absent</th>
                        <th className="p-2 border border-slate-400 text-center">Surplus</th>
                        <th className="p-2 border border-slate-400 text-center">Percentage</th>
                      </tr>
                    </thead>
                    <tbody>
                      {!d.tradeMatrix || d.tradeMatrix.length === 0 ? (
                        <tr><td colSpan={8} className="p-6 text-center text-slate-500 font-mono">No trade manpower data found.</td></tr>
                      ) : (
                        d.tradeMatrix.map((t: any, i: number) => (
                          <tr key={i} className="border-b border-slate-300 font-mono">
                            <td className="p-2 border border-slate-300 text-center">{i + 1}</td>
                            <td className="p-2 border border-slate-300 font-bold font-sans">{t.trade}</td>
                            <td className="p-2 border border-slate-300 text-center font-bold text-slate-800">{t.authorized}</td>
                            <td className="p-2 border border-slate-300 text-center font-bold text-blue-900">{t.held}</td>
                            <td className="p-2 border border-slate-300 text-center text-emerald-900 font-bold">{t.present}</td>
                            <td className="p-2 border border-slate-300 text-center text-amber-900 font-bold">{t.absent !== undefined ? t.absent : (t.held - t.present)}</td>
                            <td className="p-2 border border-slate-300 text-center text-purple-900 font-bold">{t.surplus !== undefined ? t.surplus : Math.max(0, t.held - t.authorized)}</td>
                            <td className="p-2 border border-slate-300 text-center font-bold">{t.percentage}%</td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Signature Blocks */}
        <div className="pt-16 grid grid-cols-2 gap-12 font-mono text-xs">
          <div className="text-center space-y-1">
            <div className="border-t border-slate-900 w-48 mx-auto pt-1 font-bold">
              Second-in-Command (2IC)
            </div>
            <div className="text-[10px] text-slate-600">55 Field Ambulance</div>
            <div className="text-[10px] text-slate-500">10 Infantry Division</div>
          </div>

          <div className="text-center space-y-1">
            <div className="border-t border-slate-900 w-48 mx-auto pt-1 font-bold">
              Commanding Officer (CO)
            </div>
            <div className="text-[10px] text-slate-600">55 Field Ambulance</div>
            <div className="text-[10px] text-slate-500">10 Infantry Division</div>
          </div>
        </div>
      </div>
    </div>
  );
};
